include ../../../extra.mk

STATIC_PIC_LIB_NOINST = ${LIBMOWGLI_SHARED_LINEBUF}
STATIC_LIB_NOINST = ${LIBMOWGLI_STATIC_LINEBUF}

SRCS = linebuf.c

INCLUDES = linebuf.h

include ../../../buildsys.mk

includesubdir = $(PACKAGE)/linebuf

CPPFLAGS += -I. -I.. -I../../.. -DMOWGLI_CORE

