include ../../../extra.mk

STATIC_PIC_LIB_NOINST = mowgli.linebuf.lib.a
STATIC_LIB_NOINST = mowgli.linebuf.a

SRCS = linebuf.c

INCLUDES = linebuf.h

include ../../../buildsys.mk

includesubdir = $(PACKAGE)/linebuf

CPPFLAGS += -I. -I.. -I../../.. -DMOWGLI_CORE

